N = int(input())
user_input = input("Enter numbers separated by spaces: ")
distance = list(map(int, user_input.split()))
N = int(input())
user_input = input("Enter numbers separated by spaces: ")
fuels = list(map(int, user_input.split()))
AtoB = int(input())
E = int(input())
print(N)
print(distance)
print(N)
print(fuels)
print(AtoB)
print(E)